export function createState() {
  return {
    city: null,
    userLat: null,
    userLng: null,
    locationGranted: false,
    usingPortFallback: false,
    totalMins: 0,
    cdownMins: 0,
    cdownTimer: null,
    mMap: null,
    dMap: null,
    homeMap: null,
    mReady: false,
    dReady: false,
    homeMapReady: false,
    mUserPin: null,
    dUserPin: null,
    currentPlace: null,
    selectedMapPlaceId: null,
    dMarkers: {},
    mMarkers: {},
    homePortMarkers: [],
    itinIds: [],
    exploreBooted: false,
    ports: [],
    selectedPort: null,
    newGuides: { available: true },
    itineraryIds: [],
    searchedPlaces: [],
    itineraryDurations: {},
    itineraryRoute: null,
    itineraryRouteToken: 0,
  };
}
